# Generated by Django 2.1.4 on 2019-01-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_fields', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='docfile',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
