# Generated by Django 2.1.4 on 2019-01-20 16:53

from django.db import migrations, models
import uploads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_auto_20190116_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docfile',
            name='agreement',
            field=models.FileField(upload_to='', validators=[uploads.validators.validate_file_extension]),
        ),
    ]
