# Generated by Django 2.1.4 on 2019-01-23 21:43

from django.db import migrations, models
import uploads.validators


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_auto_20190120_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docfile',
            name='agreement',
            field=models.FileField(upload_to='uploaded_files', validators=[uploads.validators.validate_file_extension]),
        ),
    ]
