# Generated by Django 2.1.4 on 2019-02-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_auto_20190123_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDocFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_title', models.CharField(max_length=100)),
                ('new_agreement', models.FileField(upload_to='edited_files')),
            ],
        ),
    ]
