# Generated by Django 2.1.4 on 2019-02-08 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_newdocfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewDocFile',
        ),
    ]
